version: 2.1

jobs:
  build-test-lint:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-docker:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            docker build -t huylq1999/capstone_aws_devops .
            docker image ls

      - run:
          name: Push to Dockerhub
          command: |
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker push huylq1999/capstone_aws_devops

  config-infrastructure:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      - run:
          name: Install eksctl
          command: |
            pwd
            ls -la
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /bin
            chmod +x /bin/eksctl
            eksctl version

      - run:
          name: Install kubectl
          command: |
            curl -sSLo /bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x /bin/kubectl
            kubectl version --client

      - run:
          name: Install aws cli
          command: |
            ls -la
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            aws --version

workflows:
  default:
    jobs:
      - build-test-lint
      - build-docker:
          requires:
            - build-test-lint
      - config-infrastructure:
          requires:
            - build-docker